// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Crypto struct {
	ID         uuid.UUID
	CreatedAt  sql.NullTime
	UpdatedAt  time.Time
	Status     string
	CryptoKey  string
	CryptoList json.RawMessage
}
