// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Crypto struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	CryptoKey  string
	CryptoList json.RawMessage
}
