// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package database

import (
	"context"
)

const getAllCrypto = `-- name: GetAllCrypto :many
SELECT id, created_at, updated_at, crypto_key, crypto_list FROM crypto
`

func (q *Queries) GetAllCrypto(ctx context.Context) ([]Crypto, error) {
	rows, err := q.db.QueryContext(ctx, getAllCrypto)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crypto
	for rows.Next() {
		var i Crypto
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CryptoKey,
			&i.CryptoList,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
