package clientlogic

import(
    "fmt"
)

func PrintCryptoHelp() {
    fmt.Println("# Crypto Assets")
    fmt.Println("")
    fmt.Println("Available timeframes: 1h, 24h, 7d, 30d, 200d, 1y")
    fmt.Println("Timeframes are used when fetching market lists on the server.")
    fmt.Println("Lists are cached hourly per timeframe. Old lists are removed periodically.")
    fmt.Println("")

    fmt.Println("## Getting crypto market lists")
    fmt.Println("")
    fmt.Println("First, make sure the server has fetched crypto data with:")
    fmt.Println("  get crypto <timeframes...>")
    fmt.Println("")
    fmt.Println("On the client, use <get> to load lists into the client state:")
    fmt.Println("  get crypto")
    fmt.Println("      Get all available crypto lists from the server publisher.")
    fmt.Println("")
    fmt.Println("  get crypto 1h 24h")
    fmt.Println("      Get only the 1h and 24h lists (if they exist) and set them on the client.")
    fmt.Println("")

    fmt.Println("## Mutating the client state")
    fmt.Println("")
    fmt.Println("By default, commands DO NOT change the stored list; they only print results.")
    fmt.Println("Use <mutate> to both run a command and update the client state with the result.")
    fmt.Println("")
    fmt.Println("  mutate <command> crypto <command-arguments>")
    fmt.Println("      Run the command and replace the current state list with its result.")
    fmt.Println("")
    fmt.Println("Available commands after <mutate>: rank, group, filter, find, calc")
    fmt.Println("There is only one active market list per client; all commands run on that list.")
    fmt.Println("")

    fmt.Println("## Saving and switching lists")
    fmt.Println("")
    fmt.Println("Use <save> to store the current state list in the client cache with a key:")
    fmt.Println("  save crypto my_filtered_list")
    fmt.Println("      Save the current list under 'my_filtered_list'. Overwrites if the key exists.")
    fmt.Println("      Also writes the list to the Docker volume so other clients can use it.")
    fmt.Println("")
    fmt.Println("Use <switch> to change the active state list to a saved one:")
    fmt.Println("  switch crypto my_filtered_list")
    fmt.Println("      Make 'my_filtered_list' the current state list from cache or volume.")
    fmt.Println("")

    fmt.Println("## Ranking coins by price change")
    fmt.Println("")
    fmt.Println("Sort coins in ascending or descending order by price change percentage.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  rank crypto <asc|desc> <timeframe>")
    fmt.Println("")
    fmt.Println("Examples:")
    fmt.Println("  rank crypto asc 24h")
    fmt.Println("      Print a new list sorted from lowest to highest price change percentage 24h.")
    fmt.Println("")
    fmt.Println("  rank crypto desc 1h")
    fmt.Println("      Print a new list sorted from highest to lowest price change percentage 1h.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate rank crypto desc 1h")
    fmt.Println("      Sort descending and update the current state list with the sorted result.")
    fmt.Println("")

    fmt.Println("## Grouping coins by liquidity (market rank + volume)")
    fmt.Println("")
    fmt.Println("Get coins between market cap ranks and filter out coins with low liquidity.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  group crypto liquidity <min_market_rank int> <max_market_rank int> <min_volume float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  group crypto liquidity 1 200 5000000")
    fmt.Println("      Show coins ranked 1–200 with at least 5,000,000 volume.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate group crypto liquidity 1 200 5000000")
    fmt.Println("      Apply the group result to the current state list.")
    fmt.Println("")

    fmt.Println("## Grouping coins by scarcity (supply + drawdown)")
    fmt.Println("")
    fmt.Println("Identify scarce coins with limited supply and large drawdowns from ATH.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  group crypto scarcity <min_circulating_supply float64> <max_ath_change_percentage float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  group crypto scarcity 1000000 -80")
    fmt.Println("      Show coins with >= 1,000,000 circulating supply and <= -80% from ATH.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate group crypto scarcity 1000000 -80")
    fmt.Println("      Apply the group result to the current state list.")
    fmt.Println("")

    fmt.Println("## Filtering by total volume")
    fmt.Println("")
    fmt.Println("Filter coins between a minimum and maximum total volume.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  filter crypto total_volume <min_volume float64> <max_volume float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  filter crypto total_volume 1000000 50000000")
    fmt.Println("      Show coins with total_volume between 1,000,000 and 50,000,000.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate filter crypto total_volume 1000000 50000000")
    fmt.Println("      Apply the filter result to the current state list.")
    fmt.Println("")

    fmt.Println("## Filtering by market cap")
    fmt.Println("")
    fmt.Println("Filter coins between a minimum and maximum market cap.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  filter crypto market_cap <min_market_cap float64> <max_market_cap float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  filter crypto market_cap 50000000 1000000000")
    fmt.Println("      Show coins with market cap between 50M and 1B.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate filter crypto market_cap 50000000 1000000000")
    fmt.Println("      Apply the filter result to the current state list.")
    fmt.Println("")

    fmt.Println("## Filtering by price change percentage")
    fmt.Println("")
    fmt.Println("Filter coins by price change percentage over a given timeframe.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  filter crypto price_change_percentage <min_change float64> <max_change float64> <timeframe>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  filter crypto price_change_percentage -5 5 24h")
    fmt.Println("      Show coins with -5% to +5% change over 24h.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate filter crypto price_change_percentage -5 5 24h")
    fmt.Println("      Apply the filter result to the current state list.")
    fmt.Println("")

    fmt.Println("## Filtering by volatility (24h swing rate)")
    fmt.Println("")
    fmt.Println("Filter coins by their volatility based on 24h high/low swing rate.")
    fmt.Println("rate = highest_price_24h / lowest_price_24h")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  filter crypto volatile <min_rate float64> <max_rate float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  filter crypto volatile 1.05 1.50")
    fmt.Println("      Show coins whose 24h high/low ratio is between 1.05 and 1.50.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate filter crypto volatile 1.05 1.50")
    fmt.Println("      Apply the filter result to the current state list.")
    fmt.Println("")

    fmt.Println("## Filtering high-risk coins")
    fmt.Println("")
    fmt.Println("Filter high-risk coins by ATH change and total volume.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  filter crypto high_risk <max_ath_change_percentage float64> <max_total_volume float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  filter crypto high_risk -70 2000000")
    fmt.Println("      Show coins down <= -70% from ATH with volume <= 2,000,000.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate filter crypto high_risk -70 2000000")
    fmt.Println("      Apply the filter result to the current state list.")
    fmt.Println("")

    fmt.Println("## Filtering low-risk coins")
    fmt.Println("")
    fmt.Println("Filter low-risk coins by market cap rank and price change.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  filter crypto low_risk <max_market_cap_rank int> <max_price_change_percentage float64> <timeframe>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  filter crypto low_risk 100 10 24h")
    fmt.Println("      Show coins with market cap rank <= 100 and <= 10% change in 24h.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate filter crypto low_risk 100 10 24h")
    fmt.Println("      Apply the filter result to the current state list.")
    fmt.Println("")

    fmt.Println("## Finding a coin by name")
    fmt.Println("")
    fmt.Println("Search for a specific coin by its name.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  find crypto name <coin_name string>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  find crypto name bitcoin")
    fmt.Println("      Show the coin(s) whose name matches 'bitcoin'.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate find crypto name bitcoin")
    fmt.Println("      Replace the current list with only the found coin(s).")
    fmt.Println("")

    fmt.Println("## Finding new high prices")
    fmt.Println("")
    fmt.Println("Find coins that have reached a new high price compared to the previous list.")
    fmt.Println("Requires at least two cached lists for the same timeframe on the server.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  find crypto new_high_price")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  find crypto new_high_price")
    fmt.Println("      Show coins with a new high compared to the previous cached list.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate find crypto new_high_price")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Finding new low prices")
    fmt.Println("")
    fmt.Println("Find coins that have reached a new low price compared to the previous list.")
    fmt.Println("Requires at least two cached lists for the same timeframe on the server.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  find crypto new_low_price")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  find crypto new_low_price")
    fmt.Println("      Show coins with a new low compared to the previous cached list.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate find crypto new_low_price")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Finding high price spikes")
    fmt.Println("")
    fmt.Println("Find coins with a strong price spike over a timeframe.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  find crypto high_price_spike <min_price_change_percentage float64> <timeframe>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  find crypto high_price_spike 20 24h")
    fmt.Println("      Show coins with >= 20% price increase in 24h.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate find crypto high_price_spike 20 24h")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Finding potential rallies")
    fmt.Println("")
    fmt.Println("Find coins with large potential upside remaining to their ATH.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  find crypto potential_rally <max_ath_change_percentage float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  find crypto potential_rally -60")
    fmt.Println("      Show coins that are at most -60% below their ATH.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate find crypto potential_rally -60")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Finding possible inflation risks / token unlocks")
    fmt.Println("")
    fmt.Println("Find coins with large supply value and relatively low market cap rank.")
    fmt.Println("supply_value = current_price * circulating_supply")
    fmt.Println("ignored_coins = a space-separated list of coin names to ignore.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  find crypto coin_inflation <min_market_cap_rank int> <min_supply_value float64> <ignored_coins>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  find crypto coin_inflation 300 1000000000 tether usdc")
    fmt.Println("      Show coins with rank >= 300 and supply_value >= 1,000,000,000,")
    fmt.Println("      ignoring 'tether' and 'usdc'.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate find crypto coin_inflation 300 1000000000 tether usdc")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Calculating daily volatility")
    fmt.Println("")
    fmt.Println("Calculate the daily volatility range for each coin.")
    fmt.Println("volatility = (high_24h - low_24h) / current_price")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  calc crypto volatility <min_volatility float64> <max_volatility float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  calc crypto volatility 0.05 0.30")
    fmt.Println("      Show coins with daily volatility between 5% and 30%.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate calc crypto volatility 0.05 0.30")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Calculating growth potential")
    fmt.Println("")
    fmt.Println("Estimate growth potential from current price to ATH within rank constraints.")
    fmt.Println("growth_potential = (ATH - current_price) / current_price * 100")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  calc crypto growth_potential <min_potential float64> <max_market_cap_rank int>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  calc crypto growth_potential 50 200")
    fmt.Println("      Show coins with at least 50% growth potential and rank <= 200.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate calc crypto growth_potential 50 200")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Calculating liquidity")
    fmt.Println("")
    fmt.Println("Calculate coin liquidity and filter by a minimum value.")
    fmt.Println("liquidity = total_volume / market_cap")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  calc crypto liquidity <min_liquidity float64>")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  calc crypto liquidity 0.10")
    fmt.Println("      Show coins with liquidity >= 0.10.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate calc crypto liquidity 0.10")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")

    fmt.Println("## Calculating trend strength")
    fmt.Println("")
    fmt.Println("Calculate a trend strength index for coins using 24h data.")
    fmt.Println("Make sure you are operating on a list that has the 24h timeframe.")
    fmt.Println("")
    fmt.Println("Command:")
    fmt.Println("  calc crypto trend_strength")
    fmt.Println("")
    fmt.Println("Example:")
    fmt.Println("  calc crypto trend_strength")
    fmt.Println("      Show coins with their calculated trend strength values.")
    fmt.Println("")
    fmt.Println("Mutate example:")
    fmt.Println("  mutate calc crypto trend_strength")
    fmt.Println("      Apply the result to the current state list.")
    fmt.Println("")
}